import { Category, Product, Order, Customer, UserProfile } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-cuidado-facial',
    name: 'Cuidado facial',
    slug: 'cuidado-facial',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8rLSfG_D_RYH00eIDC2wIW5h045skQEiblXMef8bBCq8L_cyioX_VDt5j7XX3yMGwhGuiGTyGZ7MhGN58SxC5F0EidRT3IFIiL5-j86aNBNqOaFm7C_Dw07grcJfvDX1CGXM_GxW3oZpFHLa0MyEJt2tFDFIXRpTKTdM6uf8ia6h4k9iIY5rC18h40DQKAuaPs0-vMJgFGxRBve1DL3SbsVJ-Nhs9uz1xyIDu2TWcKFGOUU5U6yyy',
    sortOrder: 1,
  },
  {
    id: 'cat-joyeria',
    name: 'Joyería',
    slug: 'joyeria',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDBQQ6eL3Rm7D1GJtwX8NuVDjhiqNMKnYdstC9R-GCwIPk7umRE2ImGHCTdmu8ojCS8pzGuoHU4l3zltxXINjwtrUUBsIltv-gXS4zCqSuXjWAnRpEm9KC9r7-UybRrVqM_uujfeemN29TEnSjGBVy7ryUMdzrWTQw_8CE0yxfEqsqEOnyVVqGuz0VsufmHEfTElNoagdSzo6vSWBxckeRIVUfiW3BzTN_W7IorfKzCseK6_wQjwxKL',
    sortOrder: 2,
  },
  {
    id: 'cat-bolsos',
    name: 'Bolsos',
    slug: 'bolsos',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBKZkuZW3jY3Funi71vkoovD-m29Vl1-dq4DKL9WVz8uF0qOVmhceUj9DzgMxROhlqerTJzJy_lWrJ-7C-kgQvvmn9qQ_65xOspLwtk4gSbrDs8RsAHjw2cJDmNDc32-2NIZXVFj-gg6m_6aoNfnK_M6-ip-iOtgAdnoCK50nLV_AJ3Zf-rsnWSgEkHn4cdmbsDWRc-oOsY1xHOS9cv5l2n9LAJUTCC0m9U0WJoXr9fbimW8p8dI6wu',
    sortOrder: 3,
  },
  {
    id: 'cat-1',
    name: 'Cosméticos',
    slug: 'cosmeticos',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCTfJiqLzXxa9LWJyYJzjfvz95_Psc1SEDN4LpwVLEawALRl6y0cY1mNDO9FkzQ2faaHehTjJbgkYckqYtK99Kyuk5czXtFHsOCWGPYRZ4PCX8nUPmu3gfbz5HyKdILhpXaTCM47KWOwaOn_ST7kyTUQ8sTE5sSnGXLl8baTd97Ja-NNjELpOUciXK0-aETceQ-D5HbNE9lU0iE_O1eAjjp7W9tDB1ieE1hQAm9fPqDnzpPfdTB-AIS',
    sortOrder: 4,
  },
  {
    id: 'cat-2',
    name: 'Esmaltes',
    slug: 'esmaltes',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCzTJYjQ_8ph0uKmdg6L9hGR5zlS92QdpvH2uhCnHlorHfX9bzcFpEB9BZdTqYIJCTd_0hgM5Xx804MymspMMWduUuLvt76CTnzRIm71q4G1HqwMhaaltqAMBiEQF_zvDc8mzcSFiIvM_F5gB0_SpnhwcS0Cs64M-L0thRElxql_ynbTmugLMxps8HWug1HJ4Tm_27W0NjE4xqxrR_c8r0B1zH0rDOxyoIq2sVCTbUHx9alFX16o2wH',
    sortOrder: 5,
  },
  {
    id: 'cat-3',
    name: 'Accesorios',
    slug: 'accesorios',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC1Hx3vakDmSlopg89FmsFh9JZAa3-ehcgyOyud7U1unoUDE4NU0XU2Nj8dIbv0wxFzzkY_75s1VeJhFxm4d55mCvg_aCouZizsc-WWwIvOcxzTH0Jgtd8N6lin2EAYNaiHW6RxojbTfcMpGPsMwnOUrACmSMRtNsKZoMbyKeWEGqvqYjmGNAregP_ue3V2AyaMzmjSyYBL7PCPoz-LIabu4-dJW_QeqxHHOz5mog6EQKR7juwJ2aEk',
    sortOrder: 6,
  },
  {
    id: 'cat-4',
    name: 'Tratamientos',
    slug: 'tratamientos',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBOvmHFw1wnWEl8aGFZrDHOjPsIG1LazoOtwwklPd7-XDX9AnVRGbCKwHAxI1ScgAzQkXS2tAgpXyPztMZVxDLcVKVP67TnqHh_dhNlzTyt6RAGEbYBq6okP6IKfxlDbSArftkMmVAW1jLRd_pqa_LManm3OpfhvaJipVPijy2ggLkgpl7-v1p_otaZEAk1aIMCCO8-Asuo9SLN7mRnpzbmW9uMuMDre10afGIdQZvioR0RSETUHJ9J',
    sortOrder: 7,
  },
  {
    id: 'cat-5',
    name: 'Tintes',
    slug: 'tintes',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBExvLjwBNa0LP6PKEzjf0loo-hq9i_uWfA78yIGCTR_dWQJFGfp5SQZc1-DQn6wA5lL2s88OVpRs9J3ofCpTn9mpDljSkSjQwYL-JY_hF99h2NjOCXqSTNDHnSeZUvVavkrSTCSUqKrARZLJ3tnAVEjJ6-qVs_GSRfPO3LXclBKq-7xD1rp-Tbuw4wfw-b3e59s48yfBO_vvwbEEOFTObiM-5WmPKAp85vy1AaM0m8WloltCn_AFdg',
    sortOrder: 8,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    sku: 'ML-CAP-001',
    name: 'Tratamiento Capilar Oro',
    category: 'Tratamientos',
    categorySlug: 'tratamientos',
    price: 85000,
    stock: 18,
    stockThreshold: 5,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDmMaZXimDbMVSGwOAWaYFf3sx7xnahnCK3uAd63TvdyGHtArVYTWZb-WTHkPlTCE5sQ2x_tT8klzO8oz83LcJKH9zrC8u6BnFwkYXVzZDiCUf5F7pwKfz3Rjbp6tN-vZFHQTGLXF-kJS-v_GTfWlpfIUufHJg7qhK7W26uwLt7NNCgydr2rxYyGhsZIiVGOyX1nNiiYhRwpUAuk2wmeeM9Kd911LoDyO8vZNELFzdMZjLExnm4PBwt',
    galleryUrls: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDBRtAH_hUp93_iZeEYPYvrjfIJviUJkihzYTY1-tfSfJRy4Qh7CNjechCZ1WzCA4ubl_gHvFTyIRCp85rX7Q1vHzl-DILpvThVo5A1g7lRoR1IEFCnXPzC-k2baU0oLlRO_-QbJzXxEj6hVCg5I8jFUASNjpgt98TgIBlWzLK9HH_w78LZZiECn4Kt7NY9jp7uIAj0Pj3nzTWqGh_OCaMLYRV7q4A3biJHyJaJtVMDCSVmGcvju_Va',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDG3GgHGosoACKiWUwym4DMdIdIAOKVz82WSFC8mKD2UKoucclsltVhv0mWUgKICIP39Zrixf4lcL_VPrg0EL235aKJJJBEdxggerW0OCb75FoCnZ1t7o30Gq2N93eL9UpHeNxisAUM-dhM3dLTKmBEAuG8q_stBAo1uTXG5hAr4822UFUQxZjWICGwXe4upvtjkY_mQkMdDIC9x6QD_MktBV8em-hMMnwiuJQR4uRoE6SpY0JuWMeP',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuC2nA4WAjjWtq6PsHo3g3RRZP4Ew3mf4DmPeTw4XK6ut71TSVxCShe61EgB1dfXpX1ekoKz2uwK0SPaxbtig7HYdaABnbMQtigxg3pVapTEdS2EKg24fy46UB9JpWnlyL9zpHbrmvCrQTlpCbjuQ7h0zCPT05G1a2E90Nh8a5JrcohoLrFqF3xMWpJkvSG6u-6JCtBkR1EvKCU-vHyRUPfI7u5THaIlEg-7nYmqn3gPP3vX5JAcmfQ0',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAMScOdi90ZmP1G4lwi71yLWO3yeBfQiCBsHKG0df60ApArJRRQxYGlCaHxRjtGjawlqySg6oqbo4IMA11wZul3ebxWZir7mqJO5kzD1ATBQGqbK8v_53AobnHFXqTrZHVyjc2o5_F4AqKdKQ9Mk7_2mO-BCv-eqXIQHPATBZ6OdS0XFcsepHiw0gKtGGhzV6SG_Uku5R4lcnT6LDun2K1kq0_RRrqwcNxn-wR5dBYgcio_Cl4WZGlv',
    ],
    description: 'Nuestro Tratamiento Capilar Oro es la culminación de años de investigación botánica para crear la fórmula perfecta que atienda las necesidades específicas del cabello latino. Rico en antioxidantes y vitaminas esenciales, penetra profundamente en la fibra capilar para reparar el daño causado por el clima, tratamientos químicos y herramientas de calor.',
    specifications: 'Ingredientes: Aceite de Argán 100% puro, Micro-partículas de oro 24k micronizado, Vitamina E, Extracto de Camelia. Contenido neto: 50 ml / 1.7 fl oz. Modo de uso: Aplicar 2-3 gotas de medios a puntas en cabello húmedo o seco.',
    rating: 4.8,
    reviewsCount: 128,
    isFeatured: true,
    isNew: true,
    createdAt: '2024-09-01T10:00:00Z',
  },
  {
    id: 'prod-2',
    sku: 'ML-LIP-001',
    name: "Labial Mate 'Fuego Latino'",
    category: 'Cosméticos',
    categorySlug: 'cosmeticos',
    price: 35000,
    stock: 4, // Low stock triggers warning
    stockThreshold: 5,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8ngAjPhkXUydp8bPtov_aZ6JrQSdnVp54sJrcGFoRn9PgpnJISUCSBUKAmzX3LxRSa4zfAHm7UhMSuQX8gTQcDsAPwyJTfApxbIumJr6jRaplohGX5zEHqvA1voXnXyTFqR9xIcRf4vIb4roLCBbD4cVhlcrA6V_FJ5wAF22OgB11u1ADWwZOPwwid9bzayFzqoqneL-kL3_KChwJA6BwED55wM6bJmf7y3UfuTWQaHKbDpKXlKxQ',
    galleryUrls: [],
    description: 'Color rojo intenso de acabado aterciopelado de alta fijación. Formulado con manteca de karité para mantener los labios hidratados sin cuartearse durante 16 horas continuas.',
    specifications: 'Acabado: Mate aterciopelado. Duración: Hasta 16 horas. Hipoalergénico y libre de parabenos.',
    rating: 5.0,
    reviewsCount: 128,
    isFeatured: true,
    isNew: false,
    createdAt: '2024-09-05T12:00:00Z',
  },
  {
    id: 'prod-3',
    sku: 'ML-PAL-001',
    name: "Paleta 'Tierra Dorada'",
    category: 'Cosméticos',
    categorySlug: 'cosmeticos',
    price: 75000,
    stock: 22,
    stockThreshold: 5,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB8Cz_VNx9_vp_gLyKCdLE8WTM5Vs2H8uQHiIi3LCwAuXU8US93zEIHiCdB_exLbD8PxeRS42vJCZmVFbj7w4mLpEUSBuVmvf8B_Z0qqrowrehtpHfW7Tw1APTLrnwNSjNVwdd_Ecye9GnmHacsSdKrAh1AlmuyED-gHu3cLV5jkYl2W8p8lZOO-0CYBHAUcsR-82oKpjclLirG1pM5vvSN9aGfxAeoa6l0Rw1Prer7UdxCNrhoacZ4',
    galleryUrls: [],
    description: '18 tonos cálidos inspirados en los paisajes latinoamericanos, combinando mates suaves, satinados sedosos y destellos metálicos con alta concentración de pigmento.',
    specifications: '18 sombras pigmentadas. Textura ultra sedosa. Incluye espejo panorámico interior.',
    rating: 4.2,
    reviewsCount: 15,
    isFeatured: true,
    isNew: false,
    createdAt: '2024-08-20T09:00:00Z',
  },
  {
    id: 'prod-4',
    sku: 'ML-CRE-001',
    name: 'Crema Hidratante Esencial',
    category: 'Tratamientos',
    categorySlug: 'tratamientos',
    price: 89000,
    stock: 0, // Out of stock
    stockThreshold: 5,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8rLSfG_D_RYH00eIDC2wIW5h045skQEiblXMef8bBCq8L_cyioX_VDt5j7XX3yMGwhGuiGTyGZ7MhGN58SxC5F0EidRT3IFIiL5-j86aNBNqOaFm7C_Dw07grcJfvDX1CGXM_GxW3oZpFHLa0MyEJt2tFDFIXRpTKTdM6uf8ia6h4k9iIY5rC18h40DQKAuaPs0-vMJgFGxRBve1DL3SbsVJ-Nhs9uz1xyIDu2TWcKFGOUU5U6yyy',
    galleryUrls: [],
    description: 'Tratamiento restaurador intensivo con ácido hialurónico triple peso molecular y niacinamida. Restablece la barrera de hidratación natural de la piel.',
    specifications: 'Para todo tipo de piel, incluso sensibles. No comedogénica.',
    rating: 4.9,
    reviewsCount: 210,
    isFeatured: false,
    isNew: false,
    createdAt: '2024-08-15T11:00:00Z',
  },
  {
    id: 'prod-5',
    sku: 'ML-PLA-001',
    name: 'Plancha Profesional Titanium',
    category: 'Accesorios',
    categorySlug: 'accesorios',
    price: 220000,
    stock: 14,
    stockThreshold: 5,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAXFm91B8Ujq5EHSItWqxJjwojjlzgljIpYt1Mlo81wUKz0SkI9ohEJaccBhEco9WdGGzN9T-aFZ_L9KHb2UCjLirUOjKGySlLO97vfSbLwVkkNVErPmuDxWOTVLe9VoBRek7nmFWqv9erJmn5b2KdcRktRKf_Gb5NiHMTt2GcNZd_pjy3vsMuusu7F6QyHcVT1oIbYfKUSiWN2y9GNdMZdaRwIqI6hdvFdpV72F8DNXiadCihCKx7v',
    galleryUrls: [],
    description: 'Placas de titanio ultra suaves con calentamiento instantáneo hasta 450°F (230°C). Creada especialmente para alisar y modelar cabellos gruesos o rebeldes.',
    specifications: 'Temperatura digital regulable. Cable giratorio 360° de 3 metros. Apagado automático de seguridad.',
    rating: 4.6,
    reviewsCount: 87,
    isFeatured: false,
    isNew: false,
    createdAt: '2024-08-10T14:30:00Z',
  },
  {
    id: 'prod-6',
    sku: 'ML-NAIL-001',
    name: "Set Esmaltes 'Noche Latina'",
    category: 'Esmaltes',
    categorySlug: 'esmaltes',
    price: 45000,
    stock: 31,
    stockThreshold: 5,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBE1NewuPF2u58Y_Etxj0TrEjIpS3XbT5A__VHTARP32hJ-iHOi-ZQO3d85dv5EeKfWS2ozah7Gf9GnZ83eiBhz7Iq6JbGCEOLcAOf_moD7OUq6bo7QNXfAuuowStHOBvCi5N4OFe7OInAKetk9iiwJ9SxF4r5Its9xGSPOqU0PV-_KetvMAe2bTt9kVuJffB6x43pqQ4Z0HIOVqXx0ZaB9XfRRJvsvIr-RWMg9HOBoJaV2LruKK7EC',
    galleryUrls: [],
    description: 'Trío de esmaltes de larga duración con brillo efecto gel y pincel panorámico para una aplicación precisa en una sola pasada.',
    specifications: 'Fórmula 10-Free no tóxica. Brillo espejo hasta 10 días.',
    rating: 4.3,
    reviewsCount: 34,
    isFeatured: false,
    isNew: false,
    createdAt: '2024-08-25T16:00:00Z',
  },
  {
    id: 'prod-7',
    sku: 'ML-EYE-001',
    name: 'Mascara Volumen Extremo',
    category: 'Cosméticos',
    categorySlug: 'cosmeticos',
    price: 35000,
    stock: 48,
    stockThreshold: 5,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCRnbrMrSzHOqtT7EZTnyWuO3ecxipA3_jzjXOiOYh-WdGpbRouH5jVv5FKxt6QQt-bpiiz6y8WcxIB3FqTtVbDSlOdWNzcA7NmRx3ibiwdp7Lc_OCLmal4xkNm4ouSRR972WXpVBGoPitDtapBM_rl9-a7clq9iwNJ-codx_ckGuqbmm0vqPDVCVSpRkyX5-7hbwTJH3gwVEwSzVd2K4qFp7uTxkaOj_mzQnu2MPH-llLqbRUG0cQM',
    galleryUrls: [],
    description: 'Pestañas densas, curvadas y con volumen cinematográfico. Cepillo anatómico que separa cada pestaña sin crear grumos.',
    specifications: 'Resistente al agua y al sudor. Enriquecida con aceite de ricino.',
    rating: 4.9,
    reviewsCount: 512,
    isFeatured: false,
    isNew: false,
    createdAt: '2024-09-02T18:00:00Z',
  },
  {
    id: 'prod-8',
    sku: 'ML-FOU-001',
    name: 'Base Perfección Duradera',
    category: 'Cosméticos',
    categorySlug: 'cosmeticos',
    price: 65000,
    stock: 26,
    stockThreshold: 5,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKl0P8DR6dmuxOs4NtgJV2T1LfU2_bVWVTtDtO_mybSjDmpV8B9nyV0sbUhuXcuEbtKCCp3SEnmSu73gOw9hOb98uJ3V1634esL-LybxjZFG84Mmd6MNjtZbZjbB3VnyKNScshpNE3l7WKNUVdefi2Q389HfJ2Z8c6n5vHtM2wWBGIxlTTOTO8hbAQpca_S9y3uC7ALSh74VcvnCRO9XRg2ZVaOBN39bKDQTWB9CsnyBKg5QerYo2i',
    galleryUrls: [],
    description: 'Base líquida de cobertura modulable y acabado satinado natural. Matifica zonas grasas e hidrata zonas secas para un cutis impecable.',
    specifications: 'FPS 20. Disponible en 16 subtonos latinos. Libre de aceites minerales.',
    rating: 4.7,
    reviewsCount: 94,
    isFeatured: false,
    isNew: false,
    createdAt: '2024-08-12T10:15:00Z',
  },
  {
    id: 'prod-9',
    sku: 'ML-COL-001',
    name: 'Collar Esencia Dorada',
    category: 'Joyería',
    categorySlug: 'joyeria',
    price: 120000,
    costPrice: 65000,
    stock: 45,
    stockThreshold: 5,
    brand: 'Natura',
    supplier: 'Distribuciones Beauty',
    unitMeasure: 'Unidades',
    batchNumber: 'LT-2026-0415',
    expirationDate: '2027-08-15',
    storageLocation: 'Estante A-2',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDBQQ6eL3Rm7D1GJtwX8NuVDjhiqNMKnYdstC9R-GCwIPk7umRE2ImGHCTdmu8ojCS8pzGuoHU4l3zltxXINjwtrUUBsIltv-gXS4zCqSuXjWAnRpEm9KC9r7-UybRrVqM_uujfeemN29TEnSjGBVy7ryUMdzrWTQw_8CE0yxfEqsqEOnyVVqGuz0VsufmHEfTElNoagdSzo6vSWBxckeRIVUfiW3BzTN_W7IorfKzCseK6_wQjwxKL',
    galleryUrls: [],
    description: 'Collar de diseño exclusivo bañado en oro con acabado satinado fino y delicada gema central. Hecho a mano por orfebres expertos.',
    specifications: 'Baño de oro de 24k hipoalergénico. Cadena regulable de 45 a 50 cm.',
    rating: 4.9,
    reviewsCount: 68,
    isFeatured: true,
    isNew: false,
    createdAt: '2024-07-28T15:20:00Z',
  },
  {
    id: 'prod-10',
    sku: 'ML-BOL-024',
    name: 'Bolso Noche Estrellada',
    category: 'Bolsos',
    categorySlug: 'bolsos',
    price: 285000,
    costPrice: 150000,
    stock: 5, // Low stock boundary
    stockThreshold: 5,
    brand: 'Mujer Latina Elegance',
    supplier: 'Marroquinería Artesanal',
    unitMeasure: 'Unidades',
    batchNumber: 'LT-2026-0024',
    expirationDate: '2028-12-31',
    storageLocation: 'Bodega Principal B-1',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBKZkuZW3jY3Funi71vkoovD-m29Vl1-dq4DKL9WVz8uF0qOVmhceUj9DzgMxROhlqerTJzJy_lWrJ-7C-kgQvvmn9qQ_65xOspLwtk4gSbrDs8RsAHjw2cJDmNDc32-2NIZXVFj-gg6m_6aoNfnK_M6-ip-iOtgAdnoCK50nLV_AJ3Zf-rsnWSgEkHn4cdmbsDWRc-oOsY1xHOS9cv5l2n9LAJUTCC0m9U0WJoXr9fbimW8p8dI6wu',
    galleryUrls: [],
    description: 'Elegante bolso de mano en cuero curtido artesanalmente con herrajes dorados y correa desmontable. El accesorio definitivo para eventos de gala.',
    specifications: 'Cuero genuino 100%. Forro interior en seda. Bolsillo de seguridad para tarjetas.',
    rating: 4.8,
    reviewsCount: 29,
    isFeatured: false,
    isNew: false,
    createdAt: '2024-08-01T13:40:00Z',
  },
  {
    id: 'prod-13',
    sku: 'ML-ACC-012',
    name: 'Set Anillos Minimal',
    category: 'Accesorios',
    categorySlug: 'accesorios',
    price: 45000,
    costPrice: 20000,
    stock: 0, // Agotado
    stockThreshold: 5,
    brand: 'Mujer Latina',
    supplier: 'Accesorios & Moda S.A.S.',
    unitMeasure: 'Unidades',
    batchNumber: 'LT-2026-012',
    expirationDate: '2029-01-01',
    storageLocation: 'Estante C-4',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC1Hx3vakDmSlopg89FmsFh9JZAa3-ehcgyOyud7U1unoUDE4NU0XU2Nj8dIbv0wxFzzkY_75s1VeJhFxm4d55mCvg_aCouZizsc-WWwIvOcxzTH0Jgtd8N6lin2EAYNaiHW6RxojbTfcMpGPsMwnOUrACmSMRtNsKZoMbyKeWEGqvqYjmGNAregP_ue3V2AyaMzmjSyYBL7PCPoz-LIabu4-dJW_QeqxHHOz5mog6EQKR7juwJ2aEk',
    galleryUrls: [],
    description: 'Set de anillos minimalistas de aleación hipoalergénica con baño dorado mate.',
    specifications: 'Aleación hipoalergénica, acabado mate.',
    rating: 4.6,
    reviewsCount: 42,
    isFeatured: false,
    isNew: false,
    createdAt: '2024-08-05T09:00:00Z',
  },
  {
    id: 'prod-14',
    sku: 'CF-001',
    name: 'Crema hidratante facial',
    category: 'Cuidado facial',
    categorySlug: 'cuidado-facial',
    price: 40000,
    costPrice: 25000,
    stock: 15,
    stockThreshold: 5,
    brand: 'Natura',
    supplier: 'Distribuciones Beauty',
    unitMeasure: 'Unidades',
    batchNumber: 'LT-2026-0415',
    expirationDate: '2027-08-15',
    storageLocation: 'Estante A-2',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8rLSfG_D_RYH00eIDC2wIW5h045skQEiblXMef8bBCq8L_cyioX_VDt5j7XX3yMGwhGuiGTyGZ7MhGN58SxC5F0EidRT3IFIiL5-j86aNBNqOaFm7C_Dw07grcJfvDX1CGXM_GxW3oZpFHLa0MyEJt2tFDFIXRpTKTdM6uf8ia6h4k9iIY5rC18h40DQKAuaPs0-vMJgFGxRBve1DL3SbsVJ-Nhs9uz1xyIDu2TWcKFGOUU5U6yyy',
    galleryUrls: [],
    description: 'Crema hidratante facial intensiva con ácido hialurónico y extractos botánicos naturales para uso profesional en estética y cabina facial.',
    specifications: 'Contenido neto: 50g. Textura ligera de rápida absorción.',
    rating: 4.9,
    reviewsCount: 154,
    isFeatured: true,
    isNew: true,
    createdAt: '2024-09-10T11:00:00Z',
  },
  {
    id: 'prod-11',
    sku: 'ML-CAP-002',
    name: 'Tratamiento Capilar Keratina',
    category: 'Tratamientos',
    categorySlug: 'tratamientos',
    price: 69000,
    stock: 2, // Critical stock (<= 5)
    stockThreshold: 5,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBOvmHFw1wnWEl8aGFZrDHOjPsIG1LazoOtwwklPd7-XDX9AnVRGbCKwHAxI1ScgAzQkXS2tAgpXyPztMZVxDLcVKVP67TnqHh_dhNlzTyt6RAGEbYBq6okP6IKfxlDbSArftkMmVAW1jLRd_pqa_LManm3OpfhvaJipVPijy2ggLkgpl7-v1p_otaZEAk1aIMCCO8-Asuo9SLN7mRnpzbmW9uMuMDre10afGIdQZvioR0RSETUHJ9J',
    galleryUrls: [],
    description: 'Máscara reconstructora con keratina hidrolizada y aminoácidos que restauran la elasticidad del cabello quebradizo.',
    specifications: '300 g. Libre de sulfatos.',
    rating: 4.8,
    reviewsCount: 73,
    isFeatured: false,
    isNew: false,
    createdAt: '2024-07-15T11:10:00Z',
  },
  {
    id: 'prod-12',
    sku: 'ML-NAIL-088',
    name: 'Esmalte Gel Brillo Intenso',
    category: 'Esmaltes',
    categorySlug: 'esmaltes',
    price: 25000,
    stock: 3, // Critical stock (<= 5)
    stockThreshold: 5,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCzTJYjQ_8ph0uKmdg6L9hGR5zlS92QdpvH2uhCnHlorHfX9bzcFpEB9BZdTqYIJCTd_0hgM5Xx804MymspMMWduUuLvt76CTnzRIm71q4G1HqwMhaaltqAMBiEQF_zvDc8mzcSFiIvM_F5gB0_SpnhwcS0Cs64M-L0thRElxql_ynbTmugLMxps8HWug1HJ4Tm_27W0NjE4xqxrR_c8r0B1zH0rDOxyoIq2sVCTbUHx9alFX16o2wH',
    galleryUrls: [],
    description: 'Top coat con tecnología de secado rápido que sella el color y otorga una protección anti-descascarillado.',
    specifications: '15 ml. Secado al aire en 60 segundos sin lámpara UV.',
    rating: 4.7,
    reviewsCount: 38,
    isFeatured: false,
    isNew: false,
    createdAt: '2024-07-20T17:45:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  // 1. PENDIENTES DE PAGO (Pending payment verification from WhatsApp)
  {
    id: '#ORD-2026-0842',
    customer: 'Carmen Miranda',
    phone: '+57 310 892 4110',
    email: 'carmen.miranda@correo.com',
    city: 'Girardot',
    department: 'Cundinamarca',
    address: 'Carrera 14 # 8-22, B/ Santander',
    date: '24 Oct 2024',
    time: '14:30h',
    subtotal: 130000,
    shippingFee: 15000,
    total: 145000,
    status: 'pending',
    carrier: 'Envía',
    tracking: '',
    receiptUrl: undefined,
    receiptVerified: false,
    items: [
      {
        productId: 'prod-9',
        productName: 'Collar Elegancia Dorada',
        sku: 'ML-COL-001',
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDBQQ6eL3Rm7D1GJtwX8NuVDjhiqNMKnYdstC9R-GCwIPk7umRE2ImGHCTdmu8ojCS8pzGuoHU4l3zltxXINjwtrUUBsIltv-gXS4zCqSuXjWAnRpEm9KC9r7-UybRrVqM_uujfeemN29TEnSjGBVy7ryUMdzrWTQw_8CE0yxfEqsqEOnyVVqGuz0VsufmHEfTElNoagdSzo6vSWBxckeRIVUfiW3BzTN_W7IorfKzCseK6_wQjwxKL',
        unitPrice: 95000,
        quantity: 1,
        totalPrice: 95000,
      },
      {
        productId: 'prod-7',
        productName: 'Mascara Volumen Extremo',
        sku: 'ML-EYE-001',
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCRnbrMrSzHOqtT7EZTnyWuO3ecxipA3_jzjXOiOYh-WdGpbRouH5jVv5FKxt6QQt-bpiiz6y8WcxIB3FqTtVbDSlOdWNzcA7NmRx3ibiwdp7Lc_OCLmal4xkNm4ouSRR972WXpVBGoPitDtapBM_rl9-a7clq9iwNJ-codx_ckGuqbmm0vqPDVCVSpRkyX5-7hbwTJH3gwVEwSzVd2K4qFp7uTxkaOj_mzQnu2MPH-llLqbRUG0cQM',
        unitPrice: 35000,
        quantity: 1,
        totalPrice: 35000,
      },
    ],
    notes: 'Cliente solicitó confirmación de número de cuenta Bancolombia por chat.',
  },
  {
    id: '#ORD-2026-0845',
    customer: 'Valeria Osorio',
    phone: '+57 301 445 9012',
    email: 'valeria.osorio@correo.com',
    city: 'Medellín',
    department: 'Antioquia',
    address: 'Calle 10 Poblado # 43E-12 Apt 402',
    date: '24 Oct 2024',
    time: '11:15h',
    subtotal: 195000,
    shippingFee: 15000,
    total: 210000,
    status: 'pending',
    carrier: 'Servientrega',
    tracking: '',
    receiptUrl: undefined,
    receiptVerified: false,
    items: [
      {
        productId: 'prod-10',
        productName: 'Bolso Noche Estrellada',
        sku: 'ML-BOL-024',
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBKZkuZW3jY3Funi71vkoovD-m29Vl1-dq4DKL9WVz8uF0qOVmhceUj9DzgMxROhlqerTJzJy_lWrJ-7C-kgQvvmn9qQ_65xOspLwtk4gSbrDs8RsAHjw2cJDmNDc32-2NIZXVFj-gg6m_6aoNfnK_M6-ip-iOtgAdnoCK50nLV_AJ3Zf-rsnWSgEkHn4cdmbsDWRc-oOsY1xHOS9cv5l2n9LAJUTCC0m9U0WJoXr9fbimW8p8dI6wu',
        unitPrice: 195000,
        quantity: 1,
        totalPrice: 195000,
      },
    ],
    notes: 'Pendiente recibir comprobante de pago Nequi.',
  },

  // 2. PEDIDOS PAGADOS (Payment verified, awaiting warehouse packing and dispatch)
  {
    id: '#ORD-2026-0839',
    customer: 'Lucía Rojas',
    phone: '+57 312 908 1122',
    email: 'lucia.rojas@correo.com',
    city: 'Bogotá, D.C.',
    department: 'Cundinamarca',
    address: 'Carrera 7ma # 116-50, Oficina 601',
    documentId: 'C.C. 1.024.882.190',
    date: '23 Oct 2024',
    time: '16:45h',
    subtotal: 165000,
    shippingFee: 15000,
    total: 180000,
    status: 'paid',
    carrier: 'InterRapidísimo',
    tracking: '',
    receiptUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8k11gOXdrBwN5ATOyaIeByyisa7i6sOfTxzlrMg1MyCEw5COmvYKRsya3IL00K0a0M5rKWWVnjNSugpi7w9z4GqH7HV-kTwzjVP7R58vk3Cgue7c33oXLf3cIdA-ESBg1-My2OlJmICOmgCBYkTgS9j10wilmgj7BcJo6j0CdK2K1DdrJSNFCP69nj9hXEY5q78ntwK6rHcBLwzctpZ7mZhdQnXMak_mlCZWq_fs2OtRIEwBfi7v0',
    receiptBank: 'Bancolombia App • Transferencia Exitosa',
    receiptRef: 'ID #492817 - Ref: 2026-0839-LROJAS',
    receiptVerified: true,
    items: [
      {
        productId: 'prod-9',
        productName: 'Set Anillos Midnight Glow',
        sku: 'ML-ANI-081',
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8k11gOXdrBwN5ATOyaIeByyisa7i6sOfTxzlrMg1MyCEw5COmvYKRsya3IL00K0a0M5rKWWVnjNSugpi7w9z4GqH7HV-kTwzjVP7R58vk3Cgue7c33oXLf3cIdA-ESBg1-My2OlJmICOmgCBYkTgS9j10wilmgj7BcJo6j0CdK2K1DdrJSNFCP69nj9hXEY5q78ntwK6rHcBLwzctpZ7mZhdQnXMak_mlCZWq_fs2OtRIEwBfi7v0',
        unitPrice: 165000,
        quantity: 1,
        totalPrice: 165000,
      },
    ],
    notes: 'Transferencia validada en cuenta de ahorros empresarial.',
  },
  {
    id: '#ORD-2026-0838',
    customer: 'Camila Restrepo',
    phone: '+57 318 732 9981',
    email: 'camila.restrepo@correo.com',
    city: 'Cali',
    department: 'Valle del Cauca',
    address: 'Av San Joaquín # 14-80',
    date: '23 Oct 2024',
    time: '10:20h',
    subtotal: 83000,
    shippingFee: 15000,
    total: 98000,
    status: 'paid',
    carrier: 'Envía',
    tracking: '',
    receiptUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBM1MzVjNE57k3X4WjdVVHD4H5ivjO6Tg30F2tGkgJhm-c7xtHVGqGEhy_wZkZoRXZzH2Ubh-Bo6qMFrhKucVEcMaSqoJHzXs0Rl82LyoyQmod5i1hy7kShni6AnZh3CmeTM01sKW22XHpm32jwis3FKp8d2IXXHZgto1Rwj7N7yUoEkDxgT6PMFYpKKnbihlmWRqiIsfDOPXDchpWbPqg-2VWN-P5WjFvAbui_hevwQNjtRfsrupjR',
    receiptBank: 'Nequi Colombia',
    receiptRef: 'M982310 - Ref: CR-2026-0838',
    receiptVerified: true,
    items: [
      {
        productId: 'prod-2',
        productName: "Labial Mate 'Fuego Latino'",
        sku: 'ML-LIP-001',
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8ngAjPhkXUydp8bPtov_aZ6JrQSdnVp54sJrcGFoRn9PgpnJISUCSBUKAmzX3LxRSa4zfAHm7UhMSuQX8gTQcDsAPwyJTfApxbIumJr6jRaplohGX5zEHqvA1voXnXyTFqR9xIcRf4vIb4roLCBbD4cVhlcrA6V_FJ5wAF22OgB11u1ADWwZOPwwid9bzayFzqoqneL-kL3_KChwJA6BwED55wM6bJmf7y3UfuTWQaHKbDpKXlKxQ',
        unitPrice: 83000,
        quantity: 1,
        totalPrice: 83000,
      },
    ],
  },
  {
    id: '#ORD-2026-0835',
    customer: 'Diana Carolina Marín',
    phone: '+57 314 621 0033',
    email: 'diana.marin@correo.com',
    city: 'Pereira',
    department: 'Risaralda',
    address: 'Circunvalar # 9-45 Casa 3',
    date: '23 Oct 2024',
    time: '09:05h',
    subtotal: 305000,
    shippingFee: 15000,
    total: 320000,
    status: 'paid',
    carrier: 'Servientrega',
    tracking: '',
    receiptUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8k11gOXdrBwN5ATOyaIeByyisa7i6sOfTxzlrMg1MyCEw5COmvYKRsya3IL00K0a0M5rKWWVnjNSugpi7w9z4GqH7HV-kTwzjVP7R58vk3Cgue7c33oXLf3cIdA-ESBg1-My2OlJmICOmgCBYkTgS9j10wilmgj7BcJo6j0CdK2K1DdrJSNFCP69nj9hXEY5q78ntwK6rHcBLwzctpZ7mZhdQnXMak_mlCZWq_fs2OtRIEwBfi7v0',
    receiptBank: 'Bancolombia Transferencia',
    receiptRef: 'Trx #812903',
    receiptVerified: true,
    items: [
      {
        productId: 'prod-1',
        productName: 'Tratamiento Capilar Oro (x2)',
        sku: 'ML-CAP-001',
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDmMaZXimDbMVSGwOAWaYFf3sx7xnahnCK3uAd63TvdyGHtArVYTWZb-WTHkPlTCE5sQ2x_tT8klzO8oz83LcJKH9zrC8u6BnFwkYXVzZDiCUf5F7pwKfz3Rjbp6tN-vZFHQTGLXF-kJS-v_GTfWlpfIUufHJg7qhK7W26uwLt7NNCgydr2rxYyGhsZIiVGOyX1nNiiYhRwpUAuk2wmeeM9Kd911LoDyO8vZNELFzdMZjLExnm4PBwt',
        unitPrice: 152500,
        quantity: 2,
        totalPrice: 305000,
      },
    ],
  },

  // 3. ENVIADOS (Handed over to logistics carrier with tracking guide)
  {
    id: '#ORD-2026-0830',
    customer: 'Sofía García',
    phone: '+57 315 889 2200',
    email: 'sofia.garcia@correo.com',
    city: 'Barranquilla',
    department: 'Atlántico',
    address: 'Cra 51B # 84-10 Apt 1201',
    date: '22 Oct 2024',
    time: '18:00h',
    subtotal: 235000,
    shippingFee: 15000,
    total: 250000,
    status: 'shipped',
    carrier: 'Envía',
    tracking: 'ENV-88912736',
    receiptUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8k11gOXdrBwN5ATOyaIeByyisa7i6sOfTxzlrMg1MyCEw5COmvYKRsya3IL00K0a0M5rKWWVnjNSugpi7w9z4GqH7HV-kTwzjVP7R58vk3Cgue7c33oXLf3cIdA-ESBg1-My2OlJmICOmgCBYkTgS9j10wilmgj7BcJo6j0CdK2K1DdrJSNFCP69nj9hXEY5q78ntwK6rHcBLwzctpZ7mZhdQnXMak_mlCZWq_fs2OtRIEwBfi7v0',
    receiptBank: 'Bancolombia',
    receiptVerified: true,
    items: [
      {
        productId: 'prod-9',
        productName: 'Pulsera Eslabón Dorado 24k',
        sku: 'ML-COL-001',
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDBQQ6eL3Rm7D1GJtwX8NuVDjhiqNMKnYdstC9R-GCwIPk7umRE2ImGHCTdmu8ojCS8pzGuoHU4l3zltxXINjwtrUUBsIltv-gXS4zCqSuXjWAnRpEm9KC9r7-UybRrVqM_uujfeemN29TEnSjGBVy7ryUMdzrWTQw_8CE0yxfEqsqEOnyVVqGuz0VsufmHEfTElNoagdSzo6vSWBxckeRIVUfiW3BzTN_W7IorfKzCseK6_wQjwxKL',
        unitPrice: 235000,
        quantity: 1,
        totalPrice: 235000,
      },
    ],
  },
  {
    id: '#ORD-2026-0828',
    customer: 'Elena Mendoza',
    phone: '+57 320 401 7723',
    email: 'elena.mendoza@correo.com',
    city: 'Bucaramanga',
    department: 'Santander',
    address: 'Calle 35 # 27-09 Cabecera',
    date: '22 Oct 2024',
    time: '14:10h',
    subtotal: 100000,
    shippingFee: 15000,
    total: 115000,
    status: 'shipped',
    carrier: 'Servientrega',
    tracking: 'SRV-90182744',
    receiptUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBM1MzVjNE57k3X4WjdVVHD4H5ivjO6Tg30F2tGkgJhm-c7xtHVGqGEhy_wZkZoRXZzH2Ubh-Bo6qMFrhKucVEcMaSqoJHzXs0Rl82LyoyQmod5i1hy7kShni6AnZh3CmeTM01sKW22XHpm32jwis3FKp8d2IXXHZgto1Rwj7N7yUoEkDxgT6PMFYpKKnbihlmWRqiIsfDOPXDchpWbPqg-2VWN-P5WjFvAbui_hevwQNjtRfsrupjR',
    receiptBank: 'Daviplata',
    receiptVerified: true,
    items: [
      {
        productId: 'prod-3',
        productName: "Paleta 'Tierra Dorada'",
        sku: 'ML-PAL-001',
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB8Cz_VNx9_vp_gLyKCdLE8WTM5Vs2H8uQHiIi3LCwAuXU8US93zEIHiCdB_exLbD8PxeRS42vJCZmVFbj7w4mLpEUSBuVmvf8B_Z0qqrowrehtpHfW7Tw1APTLrnwNSjNVwdd_Ecye9GnmHacsSdKrAh1AlmuyED-gHu3cLV5jkYl2W8p8lZOO-0CYBHAUcsR-82oKpjclLirG1pM5vvSN9aGfxAeoa6l0Rw1Prer7UdxCNrhoacZ4',
        unitPrice: 100000,
        quantity: 1,
        totalPrice: 100000,
      },
    ],
  },
  {
    id: '#ORD-2026-0825',
    customer: 'Gabriela Suárez',
    phone: '+57 311 200 4599',
    email: 'gabriela.suarez@correo.com',
    city: 'Cartagena',
    department: 'Bolívar',
    address: 'Bocagrande Av San Martín # 6-30',
    date: '21 Oct 2024',
    time: '12:00h',
    subtotal: 375000,
    shippingFee: 15000,
    total: 390000,
    status: 'shipped',
    carrier: 'Coordinadora',
    tracking: 'CRD-44120988',
    receiptUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8k11gOXdrBwN5ATOyaIeByyisa7i6sOfTxzlrMg1MyCEw5COmvYKRsya3IL00K0a0M5rKWWVnjNSugpi7w9z4GqH7HV-kTwzjVP7R58vk3Cgue7c33oXLf3cIdA-ESBg1-My2OlJmICOmgCBYkTgS9j10wilmgj7BcJo6j0CdK2K1DdrJSNFCP69nj9hXEY5q78ntwK6rHcBLwzctpZ7mZhdQnXMak_mlCZWq_fs2OtRIEwBfi7v0',
    receiptBank: 'Bancolombia',
    receiptVerified: true,
    items: [
      {
        productId: 'prod-5',
        productName: 'Plancha Profesional Titanium',
        sku: 'ML-PLA-001',
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAXFm91B8Ujq5EHSItWqxJjwojjlzgljIpYt1Mlo81wUKz0SkI9ohEJaccBhEco9WdGGzN9T-aFZ_L9KHb2UCjLirUOjKGySlLO97vfSbLwVkkNVErPmuDxWOTVLe9VoBRek7nmFWqv9erJmn5b2KdcRktRKf_Gb5NiHMTt2GcNZd_pjy3vsMuusu7F6QyHcVT1oIbYfKUSiWN2y9GNdMZdaRwIqI6hdvFdpV72F8DNXiadCihCKx7v',
        unitPrice: 375000,
        quantity: 1,
        totalPrice: 375000,
      },
    ],
  },
  {
    id: '#ORD-2026-0820',
    customer: 'Natalia Torres',
    phone: '+57 317 554 3311',
    email: 'natalia.torres@correo.com',
    city: 'Manizales',
    department: 'Caldas',
    address: 'Sector Palermo Cra 23 # 67-12',
    date: '20 Oct 2024',
    time: '17:30h',
    subtotal: 135000,
    shippingFee: 15000,
    total: 150000,
    status: 'shipped',
    carrier: 'Envía',
    tracking: 'ENV-77610293',
    receiptUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBM1MzVjNE57k3X4WjdVVHD4H5ivjO6Tg30F2tGkgJhm-c7xtHVGqGEhy_wZkZoRXZzH2Ubh-Bo6qMFrhKucVEcMaSqoJHzXs0Rl82LyoyQmod5i1hy7kShni6AnZh3CmeTM01sKW22XHpm32jwis3FKp8d2IXXHZgto1Rwj7N7yUoEkDxgT6PMFYpKKnbihlmWRqiIsfDOPXDchpWbPqg-2VWN-P5WjFvAbui_hevwQNjtRfsrupjR',
    receiptBank: 'Bancolombia App',
    receiptVerified: true,
    items: [
      {
        productId: 'prod-8',
        productName: 'Base Perfección Duradera',
        sku: 'ML-FOU-001',
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKl0P8DR6dmuxOs4NtgJV2T1LfU2_bVWVTtDtO_mybSjDmpV8B9nyV0sbUhuXcuEbtKCCp3SEnmSu73gOw9hOb98uJ3V1634esL-LybxjZFG84Mmd6MNjtZbZjbB3VnyKNScshpNE3l7WKNUVdefi2Q389HfJ2Z8c6n5vHtM2wWBGIxlTTOTO8hbAQpca_S9y3uC7ALSh74VcvnCRO9XRg2ZVaOBN39bKDQTWB9CsnyBKg5QerYo2i',
        unitPrice: 135000,
        quantity: 1,
        totalPrice: 135000,
      },
    ],
  },
];

const BASE_CUSTOMERS_SEED: Customer[] = [
  {
    id: 'cust-1',
    name: 'Sofia Ramirez',
    email: 'sofia.r@email.com',
    phone: '+57 300 123 4567',
    city: 'Bogotá',
    department: 'Cundinamarca',
    address: 'Calle 93 # 14-20 Apto 402',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDD2XKn6u4zQS3d67e_QcXPOXeybb4WpvY6ORLhJdviDuK5BLbOLlm6ulwawXJ0lnBcYOcvMqg3PbfijQotwarRoeocGZwPjJys9cfpFsucYdthr0nzI4GsYyMs-PJ4s9-1odMijHUYXVmlsQ-1oM-mph7OkTe0NdfFRhyNRVC1xVdae-BAnqeu3xCPej1wxxqCo66YgjYloZmq8F6FjxaMmx7NG4Cs_f6zmIF4AtBmnlLRxfGNOjNe',
    ordersCount: 12,
    totalSpent: 1450000,
    createdAt: '2023-11-10',
  },
  {
    id: 'cust-2',
    name: 'Carmen Vargas',
    email: 'c.vargas@email.com',
    phone: '+57 315 987 6543',
    city: 'Medellín',
    department: 'Antioquia',
    address: 'Circular 4 # 73-18 El Poblado',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBRcfXRZhwQnFgstIbYZ_Uj_qFlXjD37if9SifvmNTnAwymrCQo16ui4ZQ3M1vLTrCfRqAUDvHIHwrd2LSVkMGAnZcYr7hDm9fcoRyZjq-Suh-NpNd7B7Cq58gHrCnMzRntFUQAWsKTTqExWcZVr8mf8Xi8WEVdIEpH37qzhNUE8HcBSb6vgvvVCWlWt7d-9gbGPo-FEjUbrHhcw4vpKKk9XWDNd_TdDaLjiQkVW8VaVvfA153gXnCb',
    ordersCount: 5,
    totalSpent: 620000,
    createdAt: '2024-02-14',
  },
  {
    id: 'cust-3',
    name: 'Lucia Montoya',
    email: 'lucia.m@email.com',
    phone: '+57 320 456 7890',
    city: 'Cali',
    department: 'Valle del Cauca',
    address: 'Av 6N # 26N-45 San Fernando',
    ordersCount: 2,
    totalSpent: 278000,
    createdAt: '2024-06-20',
  },
  {
    id: 'cust-4',
    name: 'Valeria Osorio',
    email: 'valeria.osorio@correo.com',
    phone: '+57 301 445 9012',
    city: 'Medellín',
    department: 'Antioquia',
    address: 'Carrera 43A # 18 Sur-135',
    ordersCount: 3,
    totalSpent: 480000,
    createdAt: '2024-05-18',
  },
  {
    id: 'cust-5',
    name: 'Carmen Miranda',
    email: 'carmen.miranda@correo.com',
    phone: '+57 310 892 4110',
    city: 'Girardot',
    department: 'Cundinamarca',
    address: 'Cra 10 # 19-33 Barrio Blanco',
    ordersCount: 1,
    totalSpent: 145000,
    createdAt: '2024-10-24',
  },
];

const COLOMBIAN_NAMES = [
  'Camila Reyes', 'Isabella Gómez', 'Mariana Ospina', 'Daniela Restrepo',
  'Paula Echeverri', 'Natalia Morales', 'Carolina Cárdenas', 'Gabriela Silva',
  'Laura Marcela Duque', 'Andrea Jaramillo', 'Juliana Castro', 'Valentina Rios',
  'Catalina Pineda', 'Alejandra Quintero', 'Vanessa Betancur', 'Manuela Henao',
  'Diana Marcela Peñuela', 'Tatiana Arango', 'Adriana Salazar', 'Paola Zuluaga',
  'Mónica Giraldo', 'Estefanía Londoño', 'Sara Meléndez', 'Ximena Cardona',
  'Lorena Barrientos', 'Claudia Patricia Hoyos', 'Lina María Marín', 'Nataly Flórez',
  'Beatriz Elena Vélez', 'Gloria Amparo Roa', 'Ana María Suescún', 'Jessica Rendón'
];

const COLOMBIAN_CITIES = [
  { city: 'Bogotá', dept: 'Cundinamarca' },
  { city: 'Medellín', dept: 'Antioquia' },
  { city: 'Cali', dept: 'Valle del Cauca' },
  { city: 'Barranquilla', dept: 'Atlántico' },
  { city: 'Bucaramanga', dept: 'Santander' },
  { city: 'Cartagena', dept: 'Bolívar' },
  { city: 'Pereira', dept: 'Risaralda' },
  { city: 'Manizales', dept: 'Caldas' },
  { city: 'Santa Marta', dept: 'Magdalena' },
  { city: 'Cúcuta', dept: 'Norte de Santander' },
  { city: 'Ibagué', dept: 'Tolima' },
  { city: 'Villavicencio', dept: 'Meta' },
  { city: 'Pasto', dept: 'Nariño' },
  { city: 'Armenia', dept: 'Quindío' },
  { city: 'Neiva', dept: 'Huila' },
  { city: 'Montería', dept: 'Córdoba' }
];

export const INITIAL_CUSTOMERS: Customer[] = (() => {
  const list: Customer[] = [...BASE_CUSTOMERS_SEED];
  let idCounter = 6;
  
  while (list.length < 156) {
    const nameIdx = (list.length - BASE_CUSTOMERS_SEED.length) % COLOMBIAN_NAMES.length;
    const cityIdx = (list.length - BASE_CUSTOMERS_SEED.length) % COLOMBIAN_CITIES.length;
    const suffixNum = Math.floor((list.length - BASE_CUSTOMERS_SEED.length) / COLOMBIAN_NAMES.length) + 1;
    const baseName = COLOMBIAN_NAMES[nameIdx];
    const name = suffixNum === 1 ? baseName : `${baseName} ${suffixNum}`;
    const slug = baseName.toLowerCase().replace(/[^a-z]/g, '.');
    const email = suffixNum === 1 ? `${slug}@correo.co` : `${slug}${suffixNum}@correo.co`;
    const loc = COLOMBIAN_CITIES[cityIdx];
    const ordersCount = (idCounter % 7) + 1;
    const totalSpent = ordersCount * (65000 + ((idCounter * 12345) % 95000));
    const phonePrefixes = ['300', '310', '315', '320', '311', '301', '318', '314'];
    const pPrefix = phonePrefixes[idCounter % phonePrefixes.length];
    const pNumber = `${100 + (idCounter % 899)} ${1000 + (idCounter * 7) % 8999}`;
    
    list.push({
      id: `cust-${idCounter}`,
      name,
      email,
      phone: `+57 ${pPrefix} ${pNumber}`,
      city: loc.city,
      department: loc.dept,
      address: `Calle ${10 + (idCounter % 90)} # ${5 + (idCounter % 40)}-${12 + (idCounter % 70)}`,
      ordersCount,
      totalSpent,
      createdAt: `2024-0${1 + (idCounter % 9)}-${10 + (idCounter % 18)}`,
    });
    idCounter++;
  }
  return list;
})();

export const DEMO_USER_PROFILE: UserProfile = {
  id: 'usr-valentina-01',
  email: 'usuario@mujerlatina.com',
  fullName: 'Valentina Restrepo',
  role: 'customer',
  phone: '+57 312 456 7890',
  documentId: 'C.C. 1.036.944.218',
  department: 'Antioquia',
  city: 'Medellín',
  address: 'Cra 45 # 12-34, Apto 501',
  avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDQBgiQ85pSSw6cK2vJFhXzUp2R3Dw04SJd-fJNatrQsrNLNbcSDL9Y1nBbLea8_AMJfndsXWqdZ30dGzRXoGp3_Prh16E0b1hCyhnKmwrn-MaVJ3JQlZGckfTs45neGHPrcaWaamdTZrTy8m2HQ9PgBrQAlNJOzHxUHAYvDLut5SIpZZ6WG-oiWiBRwvml9ZaPrxkBjv1PWKTqfQatxqKYg2akJTdhbmGDEJtj9pX5mMu1pHI4fNNh',
  memberSince: '2024',
};

export const ADMIN_USER_PROFILE: UserProfile = {
  id: 'usr-admin-ml',
  email: 'admin@mujerlatina.com',
  fullName: 'Administradora Mujer Latina',
  role: 'admin',
  phone: '+57 320 987 2232',
  department: 'Cundinamarca',
  city: 'Bogotá',
  address: 'Sede Principal Calle 93 # 11-45',
  avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBdNwwVQtlCdmCLIffs_4B-7mTe5vBcdO7JVBvf_dbsl4nAtNz1aHLVy21EcMr_VSAk0HKqaGAiXfgw7u67mUujsb8SqrunVsrB_Hz6AM4lJP09IDIlhLSNPY6OuIde7HwczlB6sk7_aIG5AyeIScVfB9f25RtvJqNrBxKELLtyab_gFMph46y-9FKnheMPlvRIvtHG5hOtjlrf3STQRcImBPjT5-UByzDqnTu4sxBAb1UpylVUboXdiHvasV00KeIsGA',
  memberSince: '2023',
};
